export const Navbar = {
  extends: 'Flex',
  gap: 'B',
  style: {
    transition: 'all 0.45s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  Link1: {
    extends: 'Box',
    tag: 'a',
    text: 'service',
    cursor: 'pointer',
    color: 'cream',
    fontSize: 'A',
    fontWeight: '400',
    padding: 'Y Z2',
    round: 'B',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    background: 'transparent',
    style: {
      fontFamily: "'Exo 2', sans-serif",
      textDecoration: 'none',
      transition: 'color 0.2s ease, background 0.2s ease',
      backdropFilter: 'blur(12px)',
    },
    ':hover': {
      background: 'rgba(255, 241, 227, 0.08)',
    },
    attr: { href: '#services' },
  },
  Link2: {
    extends: 'Box',
    tag: 'a',
    text: 'we are',
    cursor: 'pointer',
    color: 'cream',
    fontSize: 'A',
    fontWeight: '400',
    padding: 'Y Z2',
    round: 'B',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    background: 'transparent',
    style: {
      fontFamily: "'Exo 2', sans-serif",
      textDecoration: 'none',
      transition: 'color 0.2s ease, background 0.2s ease',
      backdropFilter: 'blur(12px)',
    },
    ':hover': {
      background: 'rgba(255, 241, 227, 0.08)',
    },
    attr: { href: '#about' },
  },
  Link3: {
    extends: 'Box',
    tag: 'a',
    text: 'contact',
    cursor: 'pointer',
    color: 'cream',
    fontSize: 'A',
    fontWeight: '400',
    padding: 'Y Z2',
    round: 'B',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    background: 'transparent',
    style: {
      fontFamily: "'Exo 2', sans-serif",
      textDecoration: 'none',
      transition: 'color 0.2s ease, background 0.2s ease',
      backdropFilter: 'blur(12px)',
    },
    ':hover': {
      background: 'rgba(255, 241, 227, 0.08)',
    },
    attr: { href: '#contact' },
  },
}
