import { IMG } from './images.js';
import { render } from './render.js';

export const appInit = function appInit() {
  // Inject global body-state CSS that DOMQL cannot generate from components
  (function injectBodyStateCSS() {
    const style = document.createElement('style');
    style.textContent = [
      // === Body base styles (reset.js rules not generated by DOMQL) ===
      'body{background:#000!important;color:rgba(255,241,227,1)!important;font-family:var(--font-en);font-size:18px;line-height:1.4em;letter-spacing:-0.01em;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;position:relative;width:100%;min-height:var(--app-viewport-height,100vh)}',
      '@media(max-width:1680px){body{font-size:16px}}',
      // === DOMQL atomic class overrides (incorrect hash class values) ===
      '.menuButton{display:none!important}',
      '@media(max-width:1180px),(hover:none)and(pointer:coarse){.menuButton{display:flex!important}}',
      '.navBar{gap:.5em!important}',
      '.navBar a{font-weight:400!important}',
      '.bannerTitle h1{font-family:"Exo 2",sans-serif!important}',
      '.teamMember h6{font-family:inherit!important}',
      'footer{padding-bottom:calc(6em + var(--app-fixed-bottom-clearance,0px))!important}',
      'footer input::placeholder,footer textarea::placeholder{color:rgba(255,241,227,.3)}',
      'footer input:focus,footer textarea:focus{outline:none}',
      '.logo{z-index:1600!important}',
      // === Logo intro states (body.X & not generated by DOMQL) ===
      'body.intro-active .logo{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:1600;color:transparent;transition:none}',
      'body.intro-active .logo::after{animation:logoDotPulse 1s ease-in-out infinite}',
      'body.intro-reveal .logo{color:rgba(255,241,227,1);animation:logoPulseStrong .9s ease-out 1 both}',
      'body.intro-corners-move .logo{animation:logoMove 2.8s cubic-bezier(.16,1,.3,1) both}',
      'body.is-nav-open .logo{z-index:130!important;mix-blend-mode:normal}',
      // Intro states for child elements
      'body.intro-active .globeFrame{transform:translate3d(2vw,1.5vh,0) scale(1.2)}',
      'body.intro-globe-zoom .globeFrame{animation:globeIntroZoomOut var(--globe-intro-zoom-duration,1.05s) cubic-bezier(.22,1,.36,1) forwards}',
      'body.intro-finished .globeFrame{transform:translate3d(0,0,0) scale(1)}',
      'body.intro-active .corner{position:fixed;top:50%;left:50%;right:auto;bottom:auto;transform:translate(-50%,-50%);z-index:1600;opacity:0;transition-property:opacity;transition-duration:.6s;transition-timing-function:ease}',
      'body.intro-corners .corner{opacity:1;transform:translate(-50%,-50%) translate(-2em,2em);animation:cornerPulseStrongLeft .9s ease-out 1 both}',
      'body.intro-corners-move .corner{animation:cornerToBottomLeft 3s cubic-bezier(.16,1,.3,1) both}',
      'body.intro-active .corner2{position:fixed;top:50%;left:50%;right:auto;bottom:auto;transform:translate(-50%,-50%) rotate(180deg);z-index:1600;opacity:0;transition-property:opacity;transition-duration:.6s;transition-timing-function:ease}',
      'body.intro-corners .corner2{opacity:1;transform:translate(-50%,-50%) translate(2em,-2em) rotate(180deg);animation:cornerPulseStrongRight .9s ease-out 1 both}',
      'body.intro-corners-move .corner2{animation:cornerToTopRight 3s cubic-bezier(.16,1,.3,1) both}',
      // Overlay during intro
      'body::before,body::after{content:"";position:fixed;inset:0;z-index:1500;pointer-events:none;opacity:0;transition:opacity 1s ease}',
      'body::before{background:rgba(0,0,0,1)}',
      'body::after{background:radial-gradient(circle at center,rgba(0,0,0,.16) 0%,rgba(0,0,0,.42) 100%)}',
      'body.intro-overlay::before,body.intro-overlay::after{opacity:1}',
      'body.intro-fade::before,body.intro-fade::after{opacity:0}',
      'body.intro-active:not(.intro-finished){overflow:hidden!important}',
      // Chat panel open state (all viewports)
      'body.chat-panel-open .corner,body.chat-panel-open .corner2{opacity:0!important;pointer-events:none!important}',
      'body.chat-panel-open .langButton{opacity:0;pointer-events:none}',
      'body.chat-panel-open .navBar{opacity:0;pointer-events:none}',
      'body.chat-panel-open .menuButton{opacity:0;pointer-events:none}',
      'body.chat-panel-open .logo{opacity:0;pointer-events:none}',
      // Nav open and chat panel states at <=1180px
      '@media(max-width:1180px){body.is-nav-open .langButton,body.is-nav-open .chatButton,body.is-nav-open .corner,body.is-nav-open .corner2{opacity:0!important;pointer-events:none!important}body.is-nav-open .logo{z-index:130;mix-blend-mode:normal}}',
      // Language-based font switching
      'body[data-lang="en"]{font-family:var(--font-en)}',
      'body[data-lang="ka"]{font-family:var(--font-ka-body)}',
      // Georgian language overrides for components (body[data-lang="ka"] & ancestor selector not supported by DOMQL)
      'body[data-lang="ka"] .navBar{gap:.9em}',
      'body[data-lang="ka"] .navBar a{font-family:"BPG Square Banner Caps 2013",sans-serif;font-style:normal;font-weight:400;text-transform:none;font-synthesis:none;-webkit-font-smoothing:antialiased;font-size:.9em}',
      'body[data-lang="ka"] .navBar a:hover{font-weight:400;text-transform:none}',
      '@media(max-width:1180px){body[data-lang="ka"] .navBar a{font-size:3.5em;font-weight:400}}',
      '@media(max-width:560px){body[data-lang="ka"] .navBar a{font-size:2.7em}}',
      '@media(max-width:375px){body[data-lang="ka"] .navBar a{font-size:2.5em}}',
      'body[data-lang="ka"] .banner .bannerTitle h1{font-size:6.5em}',
      '@media(max-width:768px){body[data-lang="ka"] .banner .bannerTitle h1{font-size:4.5em}}',
      '@media(max-width:560px){body[data-lang="ka"] .banner .bannerTitle h1{font-size:4.35em}}',
      '@media(max-width:480px){body[data-lang="ka"] .banner .bannerTitle h1{font-size:3.65em}}',
      '@media(max-width:390px){body[data-lang="ka"] .banner .bannerTitle h1{font-size:3.1em}}',
      '@media(max-width:320px){body[data-lang="ka"] .banner .bannerTitle h1{font-size:2.6em}}',
      'body[data-lang="ka"] .services h2{font-size:7em;max-width:7em;line-height:1em}',
      '@media(max-width:1280px){body[data-lang="ka"] .services h2{font-size:6em;max-width:7.1em}}',
      '@media(max-width:1024px){body[data-lang="ka"] .services h2{font-size:5.1em;max-width:7.2em}}',
      '@media(max-width:860px){body[data-lang="ka"] .services h2{font-size:4.3em;max-width:7.25em}}',
      '@media(max-width:768px){body[data-lang="ka"] .services h2{font-size:3.9em;max-width:7.3em}}',
      '@media(max-width:560px){body[data-lang="ka"] .services h2{font-size:3.2em;max-width:7.35em}}',
      '@media(max-width:480px){body[data-lang="ka"] .services h2{font-size:2.8em;max-width:7.4em}}',
      '@media(max-width:390px){body[data-lang="ka"] .services h2{font-size:2.45em;max-width:7.45em}}',
      '@media(max-width:320px){body[data-lang="ka"] .services h2{font-size:2.1em;max-width:7.5em}}',
      'body[data-lang="ka"] .service hgroup h3{font-family:"BPG Square Banner Caps 2013",sans-serif;font-style:normal;font-weight:400;text-transform:none;font-synthesis:none;-webkit-font-smoothing:antialiased;line-height:1em}',
      'body[data-lang="ka"] .service hgroup p{max-width:13em}',
      'body[data-lang="ka"] .circle .dot hgroup h3{font-family:var(--font-en)}',
      'body[data-lang="ka"] .circle .dot hgroup p{min-width:12em}',
      'body[data-lang="ka"] .team h2{line-height:1em}',
      'body[data-lang="ka"] .teamMember h6{font-family:"BPG Square Banner Caps 2013",sans-serif;padding:.25em 0 0 1.35em}',
      'body[data-lang="ka"] .testimonial .title img{margin-bottom:3.5em}',
      'body[data-lang="ka"] footer h2{font-family:"Exo 2",sans-serif}',
      // Stars intro animation
      'body.intro-active .starsBg img{animation:starsIntroSharp 2.6s linear both,starsFieldLoop 18s linear infinite alternate 2.6s}',
      // Chat button mobile (560px)
      '@media(max-width:560px){.chatButton{bottom:calc(1em + var(--app-fixed-bottom-clearance,0px));right:calc(1em + var(--app-safe-right,0px))}body.chat-panel-open .chatButton{top:calc(1em + var(--app-safe-top,0px));right:calc(1em + var(--app-safe-right,0px));bottom:auto}body.chat-keyboard-open #crisp-chat-overlay iframe{--chat-keyboard-crop:clamp(7rem,calc(var(--app-keyboard-inset,0px) * .42),14rem);height:calc(100% + var(--chat-keyboard-crop));transform:translateY(calc(-1 * var(--chat-keyboard-crop)))}}'
    ].join('\n');
    document.head.appendChild(style);
  })();

  // Import content data inline (no imports allowed between project files)
  const content = {
    navbar: {
      en: { service: 'service', about: 'we are', contact: 'contact' },
      ka: { service: 'სერვისი', about: 'ჩვენ ვართ', contact: 'კონტაქტი' }
    },
    banner: {
      en: { subtitle: 'Increase your sales and brand awareness with our team', title: 'Focus Agency' },
      ka: { subtitle: 'გაზარდეთ თქვენი გაყიდვები და ბრენდის ცნობადობა ჩვენი გუნდით', title: 'Focus Agency' }
    },
    services: {
      en: {
        title: 'We offer full digital services',
        items: [
          { title: 'Social Media Marketing', description: 'Content creation and advertising', image: IMG.media },
          { title: 'Google Analytics', description: 'Full Google services support', image: IMG.analytics },
          { title: 'Web Development', description: 'Website building and management', image: IMG.web },
          { title: 'Video Production', description: 'Full photo/video production', image: IMG.video }
        ]
      },
      ka: {
        title: 'ჩვენ გთავაზობთ სრულ ციფრულ მომსახურებას',
        items: [
          { title: 'სოც მედია მარკეტინგი', description: 'კონტენტის შექმნა და რეკლამა', image: IMG.media },
          { title: 'გუგლ ანალიტიკა', description: 'სრული Google სერვისების მომსახურება', image: IMG.analytics },
          { title: 'ვებ დეველოპმენტი', description: 'საიტების აწყობა და მართვა', image: IMG.web },
          { title: 'ვიდეო პროდაქშენი', description: 'სრული ფოტო/ვიდეო მომსახურება', image: IMG.video }
        ]
      }
    },
    serviceContent: {
      en: {
        socialMediaMarketing: ['Social Media Strategy','Content Planning & Calendar','Visual & Copy Content Creation','Social Media Management','Targeted Ad Campaigns','Audience Analysis & Segmentation','Brand Voice & Style Development','Performance Analytics & Reporting','Social Media Audit','Engagement Growth','Influencer Marketing','Campaign Optimization','Ad Budget Management','Crisis Communication Management','Brand Awareness Growth'],
        googleAnalytics: ['Google Analytics Setup & Monitoring','Keyword Research','On-Page SEO','Off-Page SEO / Link Building','Technical SEO Audit','Local SEO Optimization','Competitor Analysis','Content Optimization','SEO Reporting & Insights','Google Ads Campaign Setup','Search Campaign Optimization','Display Ads Management','Remarketing Campaigns','Conversion Tracking & Optimization','Analytical Reporting'],
        webDevelopment: ['Website Planning & Strategy','UI/UX Design','Front-End Development','Back-End Development','CMS Development','E-Commerce Solutions','SEO & Optimization','Maintenance & Support','Specialized Web Solutions'],
        videoProduction: ['Social-first videos (Reels, Shorts, TikTok)','Commercial / Ad video','Corporate / Brand video','Product video','Medical / Healthcare videos','Construction / Industrial videos','Aerial videography','Video content strategy','Video ad media planning (Meta, YouTube, TikTok)','Translation & subtitles in multiple languages','Video upload & YouTube SEO optimization']
      },
      ka: {
        socialMediaMarketing: ['სოციალური მედიის სტრატეგიის შემუშავება','კონტენტ პლანირება და კალენდარი','ვიზუალური და ტექსტური კონტენტის შექმნა','ოციალური ქსელების მართვა','მიზნობრივი სარეკლამო კამპანიები','აუდიტორიის ანალიზი და სეგმენტაცია','ბრენდის ტონისა და სტილის დეველოპმენტი','შედეგების ანალიტიკა და რეპორტინგი','სოციალური მედიის აუდიტი','მომხმარებელთა ჩართულობის ზრდა','ინფლუენსერ მარკეტინგი','სოციალური კამპანიების ოპტიმიზაცია','სარეკლამო ბიუჯეტის მართვა','კრიზისული კომუნიკაციების მართვა','ბრენდის ცნობადობის ამაღლება'],
        googleAnalytics: ['გუგლ ანალიტიქსის დაყენება და მონიტორინგი','საკვანძო სიტყვების კვლევა','საძიებო სისტემისთვის ოპტიმიზაცია','გარე ბმულების სტრატეგია','ტექნიკური SEO ანალიზი','ადგილობრივი SEO ოპტიმიზაცია','კონკურენტების ანალიზი','კონტენტის ოპტიმიზაცია','SEO რეპორტინგი და შედეგების ანალიზი','გუგლ Ads კამპანიების შექმნა','ძიების კამპანიების ოპტიმიზაცია','ბანერებისა და დისპლეი რეკლამების მართვა','რემარკეტინგის კამპანიები','კონვერსიის თვალთვალი და ოპტიმიზაცია','ანალიტიკური ანგარიშების მომზადება'],
        webDevelopment: ['ვებსაიტის დაგეგმვა და სტრატეგია','მომხმარებლის ინტერფეისის და გამოცდილების დიზაინი','ფრონტ-ენდ დეველოპმენტი','ბექ-ენდ დეველოპმენტი','კონტენტის მენეჯმენტის სისტემების დეველოპმენტი','ელექტრონული კომერციის გადაწყვეტები','საძიებო ოპტიმიზაცია და შესრულების გაუმჯობესება','ტექნიკური მხარდაჭერა და მოვლა','სპეციალიზებული ვებ გადაწყვეტები'],
        videoProduction: ['სოციალური ქსელებისთვის ოპტიმიზებული ვიდეოები (Reels, Shorts, TikTok)','სარეკლამო ვიდეო (Commercial / Ad video)','კორპორაციული ვიდეო / ბრენდის ვიდეო','პროდუქტის ვიდეო','მედიცინის / ჯანმრთელობის თემატური ვიდეოები','სამშენებლო / ინდუსტრიული ვიდეოები','დრონის ვიდეოგადაღება (Aerial videography)','ვიდეოს კონტენტის სტრატეგიის შემუშავება','ვიდეო რეკლამების Mediaplan-ის დაგეგმვა (Meta, YouTube, TikTok)','თარგმნა და სუბტიტრები სხვადასხვა ენაზე','ვიდეოს ატვირთვა და SEO ოპტიმიზაცია YouTube-ზე']
      }
    },
    steps: {
      en: { title: 'Flow to Work', items: [{ number: '01', title: 'initial consultation' }, { number: '02', title: 'strategy development and implementation.' }, { number: '03', title: 'review and final refinement' }] },
      ka: { title: 'სამუშაო პროცესი', items: [{ number: '01', title: 'საწყისი კონსულტაცია' }, { number: '02', title: 'სტრატეგიის შემუშავება და დანერგვა.' }, { number: '03', title: 'შეფასება და საბოლოო დახვეწა' }] }
    },
    team: {
      en: { title: 'Our Team', more: 'know us better', members: [{ role: 'Founder', name: 'Giorgi', image: IMG.choni }, { role: 'Project Manager', name: 'Liza', image: IMG.liza }, { role: 'Graphic Designer', name: 'Mariami', image: IMG.mariami }, { role: 'Videograph', name: 'Luka', image: IMG.luka }] },
      ka: { title: 'ჩვენი გუნდი', more: 'გაგვიცანით უკეთ', members: [{ role: 'დამფუძნებელი', name: 'გიორგი', image: IMG.choni }, { role: 'პროექტ მენეჯერი', name: 'ლიზა', image: IMG.liza }, { role: 'გრაფიკული დიზაინერი', name: 'მარიამი', image: IMG.mariami }, { role: 'ვიდეოგრაფი', name: 'ლუკა', image: IMG.luka }] }
    },
    testimonial: {
      en: { title: 'people talks', messages: [{ author: 'James Harisson', text: 'I had an excellent experience everything was done accurately and on time' }, { author: 'Nina Carter', text: 'The team was responsive and execution quality was consistently high.' }, { author: 'Robert Allen', text: 'Strong communication and fast delivery through the whole process.' }, { author: 'Maria Brown', text: 'They understood the brief quickly and improved our results month by month.' }, { author: 'David Smith', text: 'Everything was clear, on schedule, and aligned with our business goals.' }, { author: 'Sophia Miller', text: 'Creative ideas with practical implementation and measurable impact.' }, { author: 'Alex Johnson', text: 'Professional workflow, transparent updates, and great final output.' }] },
      ka: { title: 'ჩვენზე ამბობენ', messages: [{ author: 'ჯეიმს ჰარისონი', text: 'ძალიან კარგი გამოცდილება მივიღე ყველაფერი ზუსტად და დროულად შესრულდა.' }, { author: 'ნინა კარტერი', text: 'გუნდი ოპერატიული იყო და შესრულების ხარისხი სტაბილურად მაღალი დარჩა.' }, { author: 'რობერტ ალენი', text: 'კომუნიკაცია ძლიერი იყო და მიწოდება მთელი პროცესის განმავლობაში სწრაფად ხდებოდა.' }, { author: 'მარია ბრაუნი', text: 'ბრიფი სწრაფად გაიგეს და შედეგები თვიდან თვემდე მნიშვნელოვნად გააუმჯობესეს.' }, { author: 'დავით სმითი', text: 'ყველაფერი იყო გასაგები, ვადებში და სრულად მიბმული ბიზნეს მიზნებზე.' }, { author: 'სოფია მილერი', text: 'კრეატიული იდეები პრაქტიკულ შესრულებასთან და გაზომვად შედეგებთან ერთად.' }, { author: 'ალექს ჯონსონი', text: 'პროფესიული სამუშაო პროცესი, გამჭვირვალე განახლებები და ძლიერი საბოლოო შედეგი.' }] }
    },
    contact: {
      en: { brand: 'focus agency', form: { legend: 'have a question?', namePlaceholder: 'name', emailPlaceholder: 'email', messagePlaceholder: 'shoot a message', submit: 'send' }, details: { phoneLabel: 'call us any time', phone: '+995 595 893 399', emailLabel: 'connect with us by email', email: 'gamarjoba@focusagency.ge', socialLabel: 'Follow us' }, address: { title: "you're welcome to visit us", line1: 'Tbilisi, Saburtalo', line2: 'Alexandre Khazbegi street N24 g' }, paragraph: 'Our agency was founded with one main purpose - to support growth and success of businesses. Every client is unique to us, which is why we always listen carefully to your needs and create strategies that deliver real results.' },
      ka: { brand: 'Focus Agency', form: { legend: 'გაქვს შეკითხვა?', namePlaceholder: 'სახელი', emailPlaceholder: 'ელ-ფოსტა', messagePlaceholder: 'მოგვწერე', submit: 'გამოგზავნე' }, details: { phoneLabel: 'დაგვირეკე ნებისმიერ დროს', phone: '+995 595 893 399', emailLabel: 'დაგვიკავშირდი ელ-ფოსტაზე', email: 'gamarjoba@focusagency.ge', socialLabel: 'გამოგვყევი' }, address: { title: 'სიამოვნებით გიმასპინძლებთ ოფისში', line1: 'თბილისი, საბურთალო', line2: 'ალექსანდრე ყაზბეგის ქუჩა N24 გ' }, paragraph: 'ჩვენი სააგენტო ერთი მთავარი მიზნისთვის შეიქმნა - ხელი შევუწყოთ ბიზნესების ზრდასა და წარმატებას. თითოეული კლიენტი ჩვენთვის უნიკალურია, ამიტომ ყურადღებით ვისმენთ შენს საჭიროებებს და ვქმნით სტრატეგიებს, რომლებიც რეალურ შედეგს იძლევა.' }
    }
  };

  window.__focusContent = content;
  window.__focusLang = localStorage.getItem('lang') || 'en';
  window.__focusPreviousLang = window.__focusLang;

  // Expose render globally
  window.__focusRender = render;

  // Enforce scroll restoration
  if ('scrollRestoration' in history) history.scrollRestoration = 'manual';

  // Detect runtime flags
  const ua = navigator.userAgent || '';
  const isSafari = /Safari/i.test(ua) && !/Chrome|CriOS|Chromium|Edg|EdgiOS|Firefox|FxiOS|OPR|OPiOS|SamsungBrowser/i.test(ua);
  const isCoarsePointer = window.matchMedia('(hover: none) and (pointer: coarse)').matches;
  const isTabletOrSmaller = window.matchMedia('(max-width: 1180px)').matches;
  const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const flags = { isSafari, isCoarsePointer, isTabletOrSmaller, prefersReducedMotion, isPerformanceMode: isCoarsePointer || isTabletOrSmaller };

  if (document.body) {
    document.body.classList.toggle('is-safari', isSafari);
    document.body.classList.toggle('is-mobile-coarse', isCoarsePointer);
  }

  // Init viewport metrics
  const setMetrics = () => {
    const vv = window.visualViewport;
    const h = vv ? vv.height : window.innerHeight;
    document.documentElement.style.setProperty('--app-visual-viewport-height', h + 'px');
  };
  setMetrics();
  window.addEventListener('resize', setMetrics);
  if (window.visualViewport) {
    window.visualViewport.addEventListener('resize', setMetrics);
    window.visualViewport.addEventListener('scroll', setMetrics);
  }

  // Set initial lang on body
  document.body.dataset.lang = window.__focusLang;
  window.scrollTo(0, 0);

  // Resolve file key to CDN URL via context.files
  const files = this.context && this.context.files;
  const resolveFile = (key) => {
    const file = files && files[key];
    return (file && file.content && file.content.src) || key;
  };

  // Set static image srcs via resolved file URLs
  const setStaticImages = () => {
    const globeImg = document.querySelector('.globe');
    if (globeImg) globeImg.src = resolveFile(IMG.globe);

    // Quotation mark
    const quoteImg = document.querySelector('.testimonial [key="Img"]');
    if (quoteImg) quoteImg.src = resolveFile(IMG.quotationMark);

    // Footer street images
    const streetImgs = document.querySelectorAll('.address img');
    [IMG.street, IMG.street2].forEach((src, i) => { if (streetImgs[i]) streetImgs[i].src = resolveFile(src); });

    // Footer nav social icons (facebook, instagram)
    const footerNavImgs = document.querySelectorAll('footer nav img');
    [IMG.facebook, IMG.instagram].forEach((src, i) => { if (footerNavImgs[i]) footerNavImgs[i].src = resolveFile(src); });

    // Team member social icons (facebook, linkedin)
    document.querySelectorAll('.teamMember').forEach(member => {
      const navImgs = member.querySelectorAll('nav img');
      [IMG.facebook, IMG.linkedin].forEach((src, i) => { if (navImgs[i]) navImgs[i].src = resolveFile(src); });
    });

    // Service card button arrows
    document.querySelectorAll('.service button img').forEach((img, i) => {
      img.src = resolveFile(i % 2 === 0 ? IMG.arrow : IMG.close);
    });

    // Nav arrows (team carousel prev/next)
    const navArrowImgs = document.querySelectorAll('.navArrows button img');
    [IMG.arrowLeft, IMG.arrowRight].forEach((src, i) => { if (navArrowImgs[i]) navArrowImgs[i].src = resolveFile(src); });
  };
  setStaticImages();

  // Expose toggleCrispChat globally
  window.toggleCrispChat = function() {
    const overlay = document.getElementById('crisp-chat-overlay');
    const chatBtn = document.querySelector('.chatButton');
    if (!overlay) return;
    const isOpen = overlay.classList.toggle('is-visible');
    if (chatBtn) chatBtn.classList.toggle('is-active', isOpen);
    document.body.classList.toggle('chat-panel-open', isOpen);
    if (chatBtn) chatBtn.setAttribute('aria-expanded', String(isOpen));
    if (isOpen) {
      overlay.removeAttribute('aria-hidden');
      overlay.removeAttribute('inert');
      const iframe = document.getElementById('crisp-chat-frame');
      if (iframe && iframe.dataset.src && !iframe.src) iframe.src = iframe.dataset.src;
      document.body.dataset.chatScrollLock = '1';
    } else {
      overlay.setAttribute('aria-hidden', 'true');
      overlay.setAttribute('inert', '');
      document.body.dataset.chatScrollLock = '0';
    }
  };
};
