// Static image assets — Parcel bundles these via new URL() and gives hashed URLs
export const IMG = {
  globe: new URL('../IMAGE/globe.webp', import.meta.url).href,
  stars: new URL('../IMAGE/stars5.webp', import.meta.url).href,
  choni: new URL('../IMAGE/choni2.webp', import.meta.url).href,
  liza: new URL('../IMAGE/liza2.webp', import.meta.url).href,
  mariami: new URL('../IMAGE/mariami2.webp', import.meta.url).href,
  luka: new URL('../IMAGE/luka2.webp', import.meta.url).href,
  quotationMark: new URL('../IMAGE/quotation-mark.png', import.meta.url).href,
  facebook: new URL('../IMAGE/facebook.png', import.meta.url).href,
  instagram: new URL('../IMAGE/instagram.png', import.meta.url).href,
  linkedin: new URL('../IMAGE/linkedin.png', import.meta.url).href,
  arrow: new URL('../IMAGE/arrow.png', import.meta.url).href,
  arrowLeft: new URL('../IMAGE/arrowLeft.png', import.meta.url).href,
  arrowRight: new URL('../IMAGE/arrowRight.png', import.meta.url).href,
  close: new URL('../IMAGE/close.png', import.meta.url).href,
  send: new URL('../IMAGE/send.png', import.meta.url).href,
  media: new URL('../IMAGE/media.webp', import.meta.url).href,
  analytics: new URL('../IMAGE/analytics.webp', import.meta.url).href,
  web: new URL('../IMAGE/web.webp', import.meta.url).href,
  video: new URL('../IMAGE/video.webp', import.meta.url).href,
  street: new URL('../IMAGE/street.webp', import.meta.url).href,
  street2: new URL('../IMAGE/street2.webp', import.meta.url).href,
};
