// Static image file keys — resolved via context.files at runtime
export const IMG = {
  globe: 'globe.webp',
  stars: 'stars5.webp',
  choni: 'choni2.webp',
  liza: 'liza2.webp',
  mariami: 'mariami2.webp',
  luka: 'luka2.webp',
  quotationMark: 'quotation-mark.png',
  facebook: 'facebook.png',
  instagram: 'instagram.png',
  linkedin: 'linkedin.png',
  arrow: 'arrow.png',
  arrowLeft: 'arrowLeft.png',
  arrowRight: 'arrowRight.png',
  close: 'close.png',
  send: 'send.png',
  media: 'media.webp',
  analytics: 'analytics.webp',
  web: 'web.webp',
  video: 'video.webp',
  street: 'street.webp',
  street2: 'street2.webp',
};
