export const MenuButton = {
  tag: 'button',
  position: 'fixed',
  top: 'calc(1.5em + var(--app-safe-top, 0px))',
  right: 'calc(1.5em + var(--app-safe-right, 0px))',
  display: 'none',
  border: '1px solid rgba(255, 241, 227, 0.45)',
  borderRadius: '.1em',
  background: 'transparent',
  width: '3em',
  height: '3em',
  flexFlow: 'column',
  gap: '.35em',
  alignItems: 'center',
  justifyContent: 'center',
  cursor: 'pointer',
  padding: '0 .35em',
  transition: 'border-radius 0.25s var(--ease-io)',
  zIndex: '140',
  font: 'inherit',

  '@tabletM': {
    display: 'flex',
    top: 'calc(1.05em + var(--app-safe-top, 0px))',
    right: 'calc(1.05em + var(--app-safe-right, 0px))',
  },

  Div: {
    tag: 'div',
    height: '.15em',
    background: 'rgba(255, 241, 227, 1)',
    borderRadius: '2em',
    transformOrigin: 'center center',
    transition: 'transform 0.35s var(--ease-io), opacity 0.35s var(--ease-io), width 0.35s var(--ease-io), align-self 0.35s var(--ease-io)',
    width: '1.5em',
    alignSelf: 'flex-end',
  },

  Div_1: {
    tag: 'div',
    height: '.15em',
    background: 'rgba(255, 241, 227, 1)',
    borderRadius: '2em',
    transformOrigin: 'center center',
    transition: 'transform 0.35s var(--ease-io), opacity 0.35s var(--ease-io), width 0.35s var(--ease-io), align-self 0.35s var(--ease-io)',
    width: '1em',
    alignSelf: 'flex-end',
  },
};
