export const TeamMember = {
  minWidth: '20em',
  maxWidth: '20em',
  height: '25em',
  border: '1px solid rgba(255, 241, 227, 0.2)',
  position: 'absolute',
  left: '50%',
  top: '50%',
  round: '2em',
  overflow: 'hidden',
  opacity: '0.55',
  transform: 'scale(0.86) translateZ(-40px)',
  boxShadow: '0 10px 30px rgba(0, 0, 0, 0.25)',
  transition: 'opacity 0.2s var(--ease-io), box-shadow 0.24s var(--ease-io), border-color 0.24s var(--ease-io)',
  willChange: 'transform',

  '&.active': {
    opacity: '1',
    transform: 'scale(1) translateZ(0)',
    borderColor: 'rgba(255, 241, 227, 0.75)',
    boxShadow: '0 30px 60px rgba(0, 0, 0, 0.35)',
  },

  '::after': {
    content: "''",
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: '0',
    left: '0',
    background: 'linear-gradient(to top, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0) 100%)',
    zIndex: '2',
    pointerEvents: 'none',
    opacity: '0.85',
    transition: 'opacity 0.22s var(--ease-io)',
  },

  '&.active::after': {
    opacity: '1',
  },

  H6: {
    fontSize: '1em',
    padding: '0 0 0 1.35em',
    fontWeight: '400',
    maxWidth: 'fit-content',
    color: 'rgba(255, 241, 227, 0.7)',
    position: 'absolute',
    zIndex: '3',
    top: '1em',
    textTransform: 'uppercase',
    opacity: '0',
    transition: 'opacity 0.22s var(--ease-io), transform 0.22s var(--ease-io)',
  },

  '&.active H6': { opacity: '1' },

  H5: {
    fontSize: '2.2em',
    maxWidth: '2em',
    lineHeight: '1em',
    position: 'absolute',
    bottom: '1em',
    left: '1em',
    zIndex: '3',
    fontWeight: '900',
    opacity: '0',
    transition: 'opacity 0.22s var(--ease-io), transform 0.22s var(--ease-io)',
  },

  '&.active H5': { opacity: '1' },

  Img: {
    position: 'absolute',
    bottom: '0',
    width: '100%',
    height: '90%',
    objectFit: 'cover',
    zIndex: '1',
    transform: 'scale(0.9)',
    transition: 'transform 0.6s var(--ease-soft)',
    display: 'block',
    maxWidth: '100%',
  },

  '&.active Img': {
    transform: 'scale(1)',
  },
  '@media (max-width: 560px)': { transform: 'scale(0.9) translateZ(-20px)' },
  '@media (max-width: 480px)': { minWidth: '75%', maxWidth: '75%' },
  '@media (max-width: 375px)': { minWidth: '85%', maxWidth: '85%' },
  '@media (max-width: 350px)': { minWidth: '90%', maxWidth: '90%', height: '21em' },

  Nav: {
    extends: 'Nav',
    class: 'socialLinks',
    tag: 'nav',
    display: 'flex',
    flexDirection: 'row',
    gap: '0',
    minWidth: 'fit-content',
    maxWidth: 'fit-content',
    position: 'absolute',
    zIndex: '3',
    top: '1.2em',
    right: '1.5em',
    Link: {
      extends: 'Link3',
      display: 'flex',
      minWidth: '2em',
      maxWidth: '2em',
      minHeight: '2em',
      maxHeight: '2em',
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      Img: {
        src: 'facebook.png',
        extends: 'Img2',
        objectFit: 'contain',
        width: '100%',
        height: '100%',
        display: 'block',
        opacity: '0.7',
        maxWidth: '100%',
      },
    },
    Link_1: {
      extends: 'Link3',
      display: 'flex',
      minWidth: '2em',
      maxWidth: '2em',
      minHeight: '2em',
      maxHeight: '2em',
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      Img: {
        src: 'linkedin.png',
        extends: 'Img2',
        objectFit: 'contain',
        width: '100%',
        height: '100%',
        display: 'block',
        opacity: '0.7',
        maxWidth: '100%',
      },
    },
  },
};