export default {
  '--app-viewport-width': '100vw',
  '--app-viewport-height': '100vh',
  '--app-visual-viewport-height': '100vh',
  '--app-safe-top': 'env(safe-area-inset-top, 0px)',
  '--app-safe-right': 'env(safe-area-inset-right, 0px)',
  '--app-safe-bottom': 'env(safe-area-inset-bottom, 0px)',
  '--app-safe-bottom-stable': 'env(safe-area-max-inset-bottom, 0px)',
  '--app-safe-left': 'env(safe-area-inset-left, 0px)',
  '--app-fixed-bottom-clearance': 'max(var(--app-safe-bottom-stable), var(--app-safe-bottom))',
  '--black': 'rgba(0,0,0,1)',
  '--cream': 'rgba(255,241,227,1)',
  '--red': 'rgba(224,77,77,1)',
  '--radius-s': '0.8em',
  '--radius-m': '1.6em',
  '--radius-l': '2.6em',
  '--ease-io': 'cubic-bezier(0.4, 0, 0.2, 1)',
  '--ease-out': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  '--ease-soft': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
  '--dur-fast': '0.2s',
  '--dur-med': '0.45s',
  '--dur-slow': '0.9s',
  '--lh-tight': '0.9em',
  '--lh-compact': '1.1em',
  '--lh-body': '1.4em',
  '--tracking-tight': '-0.02em',
  '--tracking-wide': '0.06em',
  '--font-en': "'Exo 2', sans-serif",
  '--font-ka-body': "'BPG Square Banner 2013', sans-serif",
  '--font-ka-cap': "'BPG Square Banner Caps 2013', sans-serif",
}
