export const main = {
  extends: 'Page',

  onRender: function(el) {
    if (el.__initialized) return;
    el.__initialized = true;

    el.call('appInit');
    el.call('render');
    el.call('languageSwitcher');
    el.call('navbarToggle');
    el.call('navbarScrollLinks');
    el.call('contactForm');
    el.call('loadingIntro');
    el.call('bannerAnimations');
    el.call('circleRotation');
    el.call('depthCarousel');
    el.call('infiniteCarousel');
    el.call('scrollSwitcher');
    el.call('oneTimeScrollReveal');
    el.call('scrollDepth');
    el.call('scrollParallax');
    el.call('scrollOverlayShade');
    el.call('ongoingScrollMotion');
    el.call('textWave');
  },

  Logo: {
    extends: 'Logo',
    class: 'logo',
    color: 'cream',
    width: 'fit-content',
    lineHeight: '.85em',
    fontSize: '4em',
    fontWeight: '800',
    position: 'fixed',
    fontFamily: 'var(--font-en)',
    mixBlendMode: 'difference',
    zIndex: '15',
    Span: {
      text: 'F',
    },
  },
  Corner: {
    extends: 'Corner',
    class: 'corner',
    '--corner-size': '1.2em',
    width: 'var(--corner-size)',
    height: 'var(--corner-size)',
  },
  Corner_2: {
    extends: 'Corner2',
    class: 'corner2',
    '--corner-size': '1.2em',
    width: 'var(--corner-size)',
    height: 'var(--corner-size)',
  },
  Button: {
    extends: 'MenuButton',
    class: 'menuButton',
    tag: 'button',
    position: 'fixed',
    top: 'calc(1.05em + var(--app-safe-top, 0px))',
    right: 'calc(1.05em + var(--app-safe-right, 0px))',
    flow: 'column',
    border: '1px solid rgba(255, 241, 227, 0.45)',
    round: '.1em',
    background: 'transparent',
    width: '3em',
    height: '3em',
    flexFlow: 'column',
    gap: '.35em',
    align: 'center center',
    cursor: 'pointer',
    padding: '-',
    transition: 'border-radius 0.25s var(--ease-io)',
    zIndex: '140',
    font: 'inherit',
    Div: {},
    Div_1: {},
  },
  LangButton: {
    extends: 'LangButton',
    class: 'langButton',
    flow: 'column',
    align: 'center',
    gap: '-',
    maxWidth: 'fit-content',
    fontSize: '.9em',
    Button: {
      extends: 'Button',
      text: 'ქარ',
      'data-lang': 'ka',
      lang: 'ka',
    },
    Button_1: {
      extends: 'Button',
      text: 'ENG',
      'data-lang': 'en',
      lang: 'en',
    },
  },
  Button_5: {
    extends: 'ChatButton',
    class: 'chatButton',
    tag: 'button',
    backdropFilter: 'none',
    font: 'inherit',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    id: 'open-chat-btn',
    type: 'button',
    onclick: 'window.toggleCrispChat()',
    'aria-expanded': 'false',
    'aria-label': 'Open chat',
    Span: {
      text: 'chat',
    },
  },
  ChatPanelOverlay: {
    extends: 'ChatPanelOverlay',
    id: 'crisp-chat-overlay',
    'aria-hidden': 'true',
    inert: '',
    Section: {
      extends: 'Section',
      tag: 'section',
      id: 'crisp-chat-panel',
      role: 'dialog',
      'aria-modal': 'true',
      'aria-label': 'Focus Agency live chat',
      Iframe: {
        extends: 'Iframe',
        tag: 'iframe',
        id: 'crisp-chat-frame',
        title: 'Focus Agency live chat',
        'data-src': 'https://go.crisp.chat/chat/embed/?website_id=f48830e3-9049-4f5f-96bb-e91b246dcd6c',
        loading: 'eager',
        referrerpolicy: 'origin',
      },
    },
  },
  LangContent: {
    extends: 'LangContent',
    class: 'lang-content',
    backgroundAttachment: 'scroll',
    backgroundPosition: 'center top',
    backgroundSize: '100% auto',
    backgroundRepeat: 'repeat-y',
    transition: `opacity 0.25s ease,
  letter-spacing 0.25s ease,
  line-height 0.25s ease`,
    opacity: '1',
    width: '100%',
    minWidth: '100%',
    minHeight: 'var(--app-viewport-height, 100vh)',
    background: '#000',
    position: 'relative',
    isolation: 'isolate',
    animation: 'none',
    overflowX: 'clip',
    StarsBg: {
      extends: 'StarsBg',
      class: 'starsBg',
      'aria-hidden': 'true',
    },
    Overlay: {
      extends: 'Overlay',
      class: 'overlay',
    },
    Overlay2: {
      extends: 'Overlay2',
      class: 'overlay_2',
    },
    GlobeFrame: {
      extends: 'GlobeFrame',
      class: 'globeFrame',
      position: 'fixed',
      right: '-5em',
      bottom: '-5em',
      zIndex: '1',
      pointerEvents: 'none',
      transformOrigin: '64% 58%',
      'aria-hidden': 'true',
      Img: {
        extends: 'Img',
        tag: 'img',
        class: 'globe',
        alt: '',
        decoding: 'async',
      },
    },
    Nav: {
      extends: 'Nav',
      class: 'navBar',
      tag: 'nav',
      backdropFilter: 'none',
      flow: 'column',
      flexFlow: 'column',
      gap: '.5em',
      Link: {
        extends: 'Link',
        href: '#services',
      },
      Link_1: {
        extends: 'Link',
        href: '#about',
      },
      Link_2: {
        extends: 'Link',
        href: '#contact',
      },
    },
    Section: {
      extends: 'Section',
      class: 'banner',
      tag: 'section',
      width: '100%',
      maxWidth: '100%',
      position: 'relative',
      background: 'transparent',
      overflow: 'hidden',
      Hgroup: {
        extends: 'Hgroup',
        class: 'bannerTitle',
        tag: 'hgroup',
        maxWidth: '26em',
        position: 'relative',
        zIndex: '2',
        H1: {
          extends: 'H1',
          tag: 'h1',
          'data-banner': 'title',
        },
        H4: {
          extends: 'H4',
          tag: 'h4',
          'data-banner': 'subtitle',
        },
      },
    },
    Section_6: {
      extends: 'Section',
      class: 'services',
      tag: 'section',
      width: '90%',
      maxWidth: '92em',
      padding: 'X1',
      position: 'relative',
      margin: '-',
      paddingBottom: 'Z2',
      H2: {
        extends: 'H2',
        tag: 'h2',
        'data-services': 'title',
      },
      Content: {
        extends: 'Content',
        class: 'content',
        id: 'services',
        Images: {
          extends: 'Images',
          class: 'images',
          Image: {
            extends: 'Image',
            class: 'image',
          },
          Image_1: {
            extends: 'Image',
            class: 'image',
          },
          Image_2: {
            extends: 'Image',
            class: 'image',
          },
          Image_3: {
            extends: 'Image',
            class: 'image',
          },
        },
        Service: {
          extends: 'Service',
          class: 'service',
          backdropFilter: 'blur(20px) saturate(1.1)',
          width: '25em',
          height: '15em',
          padding: 'W2',
          round: 'var(--radius-l)',
          background: 'linear-gradient(140deg, rgba(224, 77, 77, .15), rgba(0, 0, 0, 0.2))',
          color: 'white',
          cursor: 'pointer',
          boxShadow: `0 10px 30px rgba(0, 0, 0, 0.15),
  inset 0 0 0 0.08em rgba(255, 255, 255, 0.1)`,
          Hgroup: {
            extends: 'Hgroup',
            H3: {
              extends: 'H3',
              tag: 'h3',
              text: 'social media marketing',
            },
            P: {
              extends: 'P',
              tag: 'p',
              text: 'Content creation and advertising',
              margin: '-',
            },
          },
          UL: {
            extends: 'UL',
            tag: 'ul',
            listStyle: 'none',
            margin: '-',
            padding: '-',
            flow: 'column',
            flexWrap: 'wrap',
            gap: '-',
            maxWidth: '100%',
            paddingLeft: '-',
          },
          Button: {
            extends: 'Button',
            tag: 'button',
            font: 'inherit',
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            type: 'button',
            Img: {
              extends: 'Img',
              src: '/IMAGE/arrow.png',
            },
            Img_1: {
              extends: 'Img',
              src: '/IMAGE/close.png',
            },
          },
        },
      },
      Nav: {
        extends: 'Nav',
        class: 'navigationDots',
        tag: 'nav',
        '--dot-hit-size': '2.25em',
        '--dot-visual-size': '1.1em',
        '--dot-ring-size': '0.12em',
        flow: 'column',
        gap: '-',
        align: 'center',
        width: 'fit-content',
        'aria-label': 'Services navigation',
        Button: {
          class: 'dot',
          'aria-label': 'Service 1',
          extends: 'Button1',
        },
        Button_1: {
          class: 'dot',
          'aria-label': 'Service 2',
          extends: 'Button1',
        },
        Button_2: {
          class: 'dot',
          'aria-label': 'Service 3',
          extends: 'Button1',
        },
        Button_3: {
          class: 'dot',
          'aria-label': 'Service 4',
          extends: 'Button1',
        },
      },
    },
    Section_7: {
      extends: 'Section',
      class: 'steps',
      tag: 'section',
      position: 'relative',
      minHeight: '72em',
      padding: 'X1',
      H2: {
        extends: 'H2',
        tag: 'h2',
        text: 'Flow to Work',
      },
      Circle: {
        extends: 'Circle',
        class: 'circle',
        width: '42em',
        height: '42em',
        border: '.5px solid cream',
        position: 'absolute',
        top: '50%',
        left: '0',
        round: '100%',
        transform: 'translate(-200px, -40%)',
        Dot: {
          extends: 'Dot',
          class: 'dot dot1',
          Hgroup: {
            extends: 'Hgroup',
            H3: {
              extends: 'H3',
              tag: 'h3',
              text: '01',
            },
            P: {
              extends: 'P',
              tag: 'p',
              text: 'initial consultation',
              margin: '-',
            },
          },
        },
        Dot_1: {
          extends: 'Dot',
          class: 'dot dot2',
          Hgroup: {
            extends: 'Hgroup',
            H3: {
              extends: 'H3',
              tag: 'h3',
              text: '02',
            },
            P: {
              extends: 'P',
              tag: 'p',
              text: 'Strategy development and implementation',
              margin: '-',
            },
          },
        },
        Dot_2: {
          extends: 'Dot',
          class: 'dot dot3',
          Hgroup: {
            extends: 'Hgroup',
            H3: {
              extends: 'H3',
              tag: 'h3',
              text: '03',
            },
            P: {
              extends: 'P',
              tag: 'p',
              text: 'Review and final refinement',
              margin: '-',
            },
          },
        },
      },
    },
    Section_8: {
      extends: 'Section',
      class: 'team',
      tag: 'section',
      width: '100%',
      background: 'transparent',
      position: 'relative',
      padding: '-',
      zIndex: '10',
      margin: '-',
      maxWidth: '1366px',
      paddingBottom: 'W1',
      H2: {
        extends: 'H2',
        tag: 'h2',
        text: 'Our Team',
      },
      Contents: {
        extends: 'Contents',
        class: 'contents',
        id: 'about',
        TeamMember: {
          extends: 'TeamMember',
          class: 'teamMember',
          H6: {
            extends: 'H6',
            tag: 'h6',
            text: 'Founder',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'Giorgi',
          },
          Img: {
            extends: 'Img',
            tag: 'img',
            display: 'block',
            maxWidth: '100%',
            src: './IMAGE/choni2.webp',
            alt: '',
            loading: 'lazy',
            decoding: 'async',
          },
        },
        TeamMember_1: {
          extends: 'TeamMember',
          class: 'teamMember',
          H6: {
            extends: 'H6',
            tag: 'h6',
            text: 'Project Manager',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'Liza',
          },
          Img: {
            extends: 'Img',
            tag: 'img',
            display: 'block',
            maxWidth: '100%',
            src: './IMAGE/liza2.webp',
            alt: '',
            loading: 'lazy',
            decoding: 'async',
          },
        },
        TeamMember_2: {
          extends: 'TeamMember',
          class: 'teamMember',
          H6: {
            extends: 'H6',
            tag: 'h6',
            text: 'Graphic Designer',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'Mariami',
          },
          Img: {
            extends: 'Img',
            tag: 'img',
            display: 'block',
            maxWidth: '100%',
            src: './IMAGE/mariami2.webp',
            alt: '',
            loading: 'lazy',
            decoding: 'async',
          },
        },
        TeamMember_3: {
          extends: 'TeamMember',
          class: 'teamMember',
          H6: {
            extends: 'H6',
            tag: 'h6',
            text: 'Videograph',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'Luka',
          },
          Img: {
            extends: 'Img',
            tag: 'img',
            display: 'block',
            maxWidth: '100%',
            src: './IMAGE/luka2.webp',
            alt: '',
            loading: 'lazy',
            decoding: 'async',
          },
        },
      },
      NavArrows: {
        extends: 'NavArrows',
        class: 'navArrows',
        zIndex: '100',
        flow: 'column',
        gap: '-',
        Button: {
          class: 'prev',
          'aria-label': 'Previous team member',
          extends: 'Button4',
        },
        Button_1: {
          class: 'next',
          'aria-label': 'Next team member',
          extends: 'Button4',
        },
      },
      Button: {
        extends: 'Button',
        class: 'more',
        text: 'know us better',
      },
    },
    Section_9: {
      extends: 'Section',
      class: 'testimonial',
      tag: 'section',
      maxWidth: 'fit-content',
      margin: '-',
      height: 'fit-content',
      padding: 'Z2',
      position: 'relative',
      zIndex: '100',
      paddingBottom: 'W1',
      width: '100%',
      Title: {
        extends: 'Title',
        class: 'title',
        Img: {
          src: './IMAGE/quotation-mark.png',
          extends: 'Img2',
        },
        H3: {
          extends: 'H3',
          tag: 'h3',
          text: 'people talks',
        },
      },
      TestimonialContent: {
        extends: 'TestimonialContent',
        class: 'testimonialContent',
        Messages: {
          extends: 'Messages',
          class: 'messages',
          P: {
            extends: 'P',
            tag: 'p',
            text: 'I had an excellent experience everything was done accurately and on time',
            margin: '-',
            'data-author': 'James Harisson',
          },
          P_1: {
            extends: 'P',
            tag: 'p',
            text: 'The team was responsive and execution quality was consistently high.',
            margin: '-',
            'data-author': 'Nina Carter',
          },
          P_2: {
            extends: 'P',
            tag: 'p',
            text: 'Strong communication and fast delivery through the whole process.',
            margin: '-',
            'data-author': 'Robert Allen',
          },
          P_3: {
            extends: 'P',
            tag: 'p',
            text: 'They understood the brief quickly and improved our results month by month.',
            margin: '-',
            'data-author': 'Maria Brown',
          },
          P_4: {
            extends: 'P',
            tag: 'p',
            text: 'Everything was clear, on schedule, and aligned with our business goals.',
            margin: '-',
            'data-author': 'David Smith',
          },
          P_5: {
            extends: 'P',
            tag: 'p',
            text: 'Creative ideas with practical implementation and measurable impact.',
            margin: '-',
            'data-author': 'Sophia Miller',
          },
          P_6: {
            extends: 'P',
            tag: 'p',
            text: 'Professional workflow, transparent updates, and great final output.',
            margin: '-',
            'data-author': 'Alex Johnson',
          },
        },
        Focus: {
          extends: 'Focus',
          class: 'focus',
          width: '25em',
          height: '15em',
          position: 'relative',
          FocusCorner: {
            extends: 'FocusCorner',
          },
          FocusCorner_1: {
            extends: 'FocusCorner',
          },
          FocusCorner_2: {
            extends: 'FocusCorner',
          },
          FocusCorner_3: {
            extends: 'FocusCorner',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'James harisson',
          },
        },
      },
    },
    Footer: {
      extends: 'Footer',
      tag: 'footer',
      width: '100%',
      zIndex: '10',
      position: 'relative',
      paddingLeft: 'W2',
      minHeight: 'fit-content',
      paddingBottom: 'calc(6em + var(--app-fixed-bottom-clearance, 0px))',
      '--footerGlow': '0',
      paddingRight: 'W2',
      H2: {
        extends: 'H2',
        tag: 'h2',
        text: 'focus agency',
      },
      Form: {
        extends: 'Form',
        tag: 'form',
        flow: 'column',
        flexFlow: 'column',
        maxWidth: '100%',
        maxHeight: 'fit-content',
        position: 'relative',
        gap: '-',
        minWidth: '100%',
        padding: '-',
        action: 'https://formspree.io/f/xqeypeyg',
        method: 'POST',
        id: 'contact',
        Legend: {
          extends: 'Legend',
          tag: 'legend',
          text: 'have a question?',
          fontSize: '1.2em',
          color: 'rgba(255, 241, 227, .7)',
          marginBottom: '.5em',
          fontWeight: '300',
          margin: '-',
        },
        Input: {
          extends: 'Input',
          tag: 'input',
          font: 'inherit',
          border: '1px solid rgba(255, 241, 227, .1)',
          fontSize: '1em',
          round: '2em',
          padding: '-',
          color: 'cream',
          margin: '-',
          background: 'transparent',
          id: 'name',
          name: 'name',
          type: 'text',
          autocomplete: 'name',
          placeholder: 'name',
        },
        Input_2: {
          extends: 'Input',
          tag: 'input',
          font: 'inherit',
          border: '1px solid rgba(255, 241, 227, .1)',
          fontSize: '1em',
          round: '2em',
          padding: '-',
          color: 'cream',
          margin: '-',
          background: 'transparent',
          id: 'email',
          name: 'email',
          type: 'email',
          autocomplete: 'email',
          placeholder: 'email',
          required: '',
        },
        Textarea: {
          extends: 'Textarea',
          tag: 'textarea',
          font: 'inherit',
          minWidth: '28em',
          maxWidth: '28em',
          padding: '-',
          background: 'transparent',
          border: '1px solid rgba(255, 241, 227, .1)',
          round: '2em',
          resize: 'none',
          color: 'cream',
          id: 'message',
          name: 'message',
          rows: '6',
          placeholder: 'shoot a message',
          required: '',
        },
        Button: {
          extends: 'Button',
          tag: 'button',
          text: 'send',
          font: 'inherit',
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          type: 'submit',
        },
        P: {
          extends: 'P',
          tag: 'p',
          margin: '-',
          position: 'absolute',
          left: '0',
          bottom: '-2.2em',
          color: 'rgba(255, 241, 227, .85)',
          fontSize: '0.84375em',
          paddingLeft: '-',
          lineHeight: '1.2',
          id: 'contact-status',
          role: 'status',
          'aria-live': 'polite',
          hidden: '',
        },
      },
      Contact: {
        extends: 'Contact',
        class: 'contact',
        marginLeft: '-',
        H5: {
          extends: 'H5',
          tag: 'h5',
          text: 'call us any time',
        },
        P: {
          extends: 'P',
          tag: 'p',
          text: '+995 595 893 399',
          margin: '-',
        },
        H5_2: {
          extends: 'H5',
          tag: 'h5',
          text: 'connect with us by email',
        },
        P_3: {
          extends: 'P',
          tag: 'p',
          text: 'gamarjoba@focusagency.ge',
          margin: '-',
        },
        H5_4: {
          extends: 'H5',
          tag: 'h5',
          text: 'Follow us',
        },
        Nav: {
          extends: 'Nav',
          class: 'socialLinks',
          tag: 'nav',
          Link: {
            Img: {
              src: './IMAGE/facebook.png',
              extends: 'Img2',
            },
            extends: 'Link3',
          },
          Link_1: {
            Img: {
              src: './IMAGE/instagram.png',
              extends: 'Img2',
            },
            extends: 'Link3',
          },
        },
      },
      Address: {
        extends: 'Address',
        class: 'address',
        position: 'relative',
        maxWidth: '100%',
        padding: 'Z2',
        marginLeft: 'auto',
        marginRight: 'W2',
        marginTop: '-',
        paddingRight: '-',
        marginBottom: 'W1',
        paddingTop: 'X2',
        paddingBottom: '-',
        paddingLeft: '-',
        minWidth: '100%',
        Hgroup: {
          extends: 'Hgroup',
          tag: 'hgroup',
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: `you're welcome to visit us`,
          },
          P: {
            extends: 'P',
            tag: 'p',
            margin: '-',
            Span: {
              text: 'Tbilisi, Saburtalo',
            },
            Span_1: {
              text: 'Alexandre Khazbegi street N24 g',
            },
          },
        },
        Img: {
          src: './IMAGE/street.webp',
          extends: 'Img2',
        },
        Img_2: {
          src: './IMAGE/street2.webp',
          extends: 'Img2',
        },
      },
      P: {
        extends: 'P',
        tag: 'p',
        text: `Our agency was founded with one main purpose — to support growth and success of businesses. Every client is
        unique to us, which is why we always listen carefully to your needs and create strategies that deliver real
        results.`,
        margin: '-',
      },
    },
  },
};