export const main = {
  extends: 'Page',

  onRender: function(el) {
    if (el.__initialized) return;
    el.__initialized = true;

    el.call('appInit');
    el.call('render');
    el.call('languageSwitcher');
    el.call('navbarToggle');
    el.call('navbarScrollLinks');
    el.call('contactForm');
    el.call('loadingIntro');
    el.call('bannerAnimations');
    el.call('circleRotation');
    el.call('depthCarousel');
    el.call('infiniteCarousel');
    el.call('scrollSwitcher');
    el.call('oneTimeScrollReveal');
    el.call('scrollDepth');
    el.call('scrollParallax');
    el.call('scrollOverlayShade');
    el.call('ongoingScrollMotion');
    el.call('textWave');
  },

  Logo: {
    extends: 'Logo',
    class: 'logo',
    Span: {
      text: 'F',
    },
  },
  Corner: {
    extends: 'Corner',
    class: 'corner',
  },
  Corner_2: {
    extends: 'Corner2',
    class: 'corner2',
  },
  Button: {
    extends: 'MenuButton',
    class: 'menuButton',
    Div: {},
    Div_1: {},
  },
  LangButton: {
    extends: 'LangButton',
    class: 'langButton',
    flow: 'column',
    align: 'center',
    gap: '-',
    maxWidth: 'fit-content',
    fontSize: '.9em',
    Button: {
      extends: 'LangBtn',
      text: 'ქარ',
      'data-lang': 'ka',
      lang: 'ka',
    },
    Button_1: {
      extends: 'LangBtn',
      text: 'ENG',
      'data-lang': 'en',
      lang: 'en',
    },
  },
  Button_5: {
    extends: 'ChatButton',
    class: 'chatButton',
    id: 'open-chat-btn',
    type: 'button',
    onclick: 'window.toggleCrispChat()',
    'aria-expanded': 'false',
    'aria-label': 'Open chat',
    Span: {
      text: 'chat',
    },
  },
  ChatPanelOverlay: {
    extends: 'ChatPanelOverlay',
    id: 'crisp-chat-overlay',
    'aria-hidden': 'true',
    inert: '',
    Section: {
      extends: 'Section',
      tag: 'section',
      id: 'crisp-chat-panel',
      role: 'dialog',
      'aria-modal': 'true',
      'aria-label': 'Focus Agency live chat',
      Iframe: {
        extends: 'Iframe',
        tag: 'iframe',
        id: 'crisp-chat-frame',
        title: 'Focus Agency live chat',
        'data-src': 'https://go.crisp.chat/chat/embed/?website_id=f48830e3-9049-4f5f-96bb-e91b246dcd6c',
        loading: 'eager',
        referrerpolicy: 'origin',
      },
    },
  },
  LangContent: {
    extends: 'LangContent',
    class: 'lang-content',
    backgroundAttachment: 'scroll',
    backgroundPosition: 'center top',
    backgroundSize: '100% auto',
    backgroundRepeat: 'repeat-y',
    transition: `opacity 0.25s ease,
  letter-spacing 0.25s ease,
  line-height 0.25s ease`,
    opacity: '1',
    width: '100%',
    minWidth: '100%',
    minHeight: '100vh',
    background: '#000',
    position: 'relative',
    isolation: 'isolate',
    animation: 'none',
    overflowX: 'clip',
    StarsBg: {
      extends: 'StarsBg',
      class: 'starsBg',
      'aria-hidden': 'true',
    },
    Overlay: {
      extends: 'Overlay',
      class: 'overlay',
    },
    Overlay2: {
      extends: 'Overlay2',
      class: 'overlay_2',
    },
    GlobeFrame: {
      extends: 'GlobeFrame',
      class: 'globeFrame',
      position: 'fixed',
      right: '-5em',
      bottom: '-5em',
      zIndex: '1',
      pointerEvents: 'none',
      transformOrigin: '64% 58%',
      'aria-hidden': 'true',
      Img: {
        extends: 'Img',
        tag: 'img',
        class: 'globe',
        alt: '',
        decoding: 'async',
      },
    },
    Nav: {
      extends: 'NavBar',
      class: 'navBar',
      Link: {
        extends: 'NavLink',
        href: '#services',
      },
      Link_1: {
        extends: 'NavLink',
        href: '#about',
      },
      Link_2: {
        extends: 'NavLink',
        href: '#contact',
      },
    },
    Section: {
      extends: 'Section',
      class: 'banner',
      tag: 'section',
      width: '100%',
      maxWidth: '100%',
      height: '100vh',
      minHeight: '100vh',
      position: 'relative',
      background: 'transparent',
      overflow: 'hidden',
      Hgroup: {
        extends: 'Hgroup',
        class: 'bannerTitle',
        tag: 'hgroup',
        maxWidth: '28em',
        position: 'absolute',
        top: '15em',
        left: '13em',
        zIndex: '4',
        '@media (max-width: 1366px) and (max-height: 768px)': { top: '10em' },
        '@media (max-height: 500px)': { top: '8em' },
        '@media (max-width: 1190px)': { left: '11em' },
        '@media (max-width: 860px)': { left: '7em' },
        '@media (max-width: 768px)': { top: '11em', left: '8em' },
        '@media (max-width: 560px)': { top: '11.2em', left: '5em', right: '1.2em' },
        '@media (max-width: 480px)': { top: '10.4em', left: '3.2em', right: '1em' },
        '@media (max-width: 390px)': { top: '9.8em', left: '2.5em' },
        '@media (max-width: 320px)': { top: '9.2em', left: '2em', right: '0.7em' },
        H1: {
          extends: 'H1',
          tag: 'h1',
          'data-banner': 'title',
          lineHeight: '0.78em',
          maxWidth: '3em',
          letterSpacing: '-0.03em',
          fontFamily: "'Exo 2', sans-serif",
          marginBottom: '0.5em',
          'body[data-lang="ka"] &': { fontSize: '6.5em' },
          '@media (max-width: 768px)': { fontSize: '5em', 'body[data-lang="ka"] &': { fontSize: '4.5em' } },
          '@media (max-width: 560px)': { fontSize: '4.85em', 'body[data-lang="ka"] &': { fontSize: '4.35em' } },
          '@media (max-width: 480px)': { fontSize: '4.15em', 'body[data-lang="ka"] &': { fontSize: '3.65em' } },
          '@media (max-width: 390px)': { fontSize: '3.6em', maxWidth: '4em', 'body[data-lang="ka"] &': { fontSize: '3.1em' } },
          '@media (max-width: 320px)': { fontSize: '3.1em', 'body[data-lang="ka"] &': { fontSize: '2.6em' } },
        },
        H4: {
          extends: 'H4',
          tag: 'h4',
          'data-banner': 'subtitle',
          fontSize: '1em',
          maxWidth: '15em',
          lineHeight: '1.4em',
          letterSpacing: '0.06em',
          marginLeft: '0.25em',
          '@media (max-width: 480px)': { fontSize: '0.9em' },
        },
      },
    },
    Section_6: {
      extends: 'Section',
      class: 'services',
      tag: 'section',
      width: '80%',
      maxWidth: '92em',
      padding: '8em 0 22em 0',
      position: 'relative',
      margin: '0 auto',
      H2: {
        extends: 'H2',
        tag: 'h2',
        'data-services': 'title',
        fontWeight: '900',
        fontSize: '9em',
        maxWidth: '5em',
        lineHeight: '0.9em',
        letterSpacing: '-0.02em',
        padding: '2.2em 0 3em 0',
        opacity: '0',
        transform: 'translateY(0.8em)',
        filter: 'blur(6px)',
        transition: 'opacity 0.3s var(--ease-io), transform 0.3s var(--ease-io), filter 0.3s var(--ease-io)',
        '&.is-visible': { opacity: '1', transform: 'translateY(0)', filter: 'blur(0)' },
        '@media (max-width: 1280px)': { fontSize: '7.6em', maxWidth: '5.1em' },
        '@media (max-width: 1024px)': { fontSize: '6.4em', maxWidth: '5.2em' },
      },
      Content: {
        extends: 'Content',
        class: 'content',
        id: 'services',
        '@media (max-width: 1180px), (hover: none) and (pointer: coarse)': {
          position: 'relative',
          top: 'auto',
        },
        '&.reveal-on-scroll': {
          opacity: '0',
          transform: 'translateY(2.8em)',
          transition: 'opacity 0.52s var(--ease-io) 0.08s, transform 0.9s cubic-bezier(0.22, 1, 0.36, 1) 0.08s',
        },
        '&.reveal-on-scroll.is-visible': {
          opacity: '1',
          transform: 'translateY(0)',
        },
        Images: {
          extends: 'Images',
          class: 'images',
          '@media (max-width: 1180px), (hover: none) and (pointer: coarse)': { pointerEvents: 'none' },
          '&.is-static': { overflow: 'hidden' },
          Image: {
            extends: 'Image',
            class: 'image',
            '@media (max-width: 1180px), (hover: none) and (pointer: coarse)': { backgroundAttachment: 'scroll' },
          },
          Image_1: {
            extends: 'Image',
            class: 'image',
            '@media (max-width: 1180px), (hover: none) and (pointer: coarse)': { backgroundAttachment: 'scroll' },
          },
          Image_2: {
            extends: 'Image',
            class: 'image',
            '@media (max-width: 1180px), (hover: none) and (pointer: coarse)': { backgroundAttachment: 'scroll' },
          },
          Image_3: {
            extends: 'Image',
            class: 'image',
            '@media (max-width: 1180px), (hover: none) and (pointer: coarse)': { backgroundAttachment: 'scroll' },
          },
        },
        Service: {
          extends: 'Service',
          class: 'service',
          backdropFilter: 'blur(20px) saturate(1.1)',
          width: '25em',
          height: '15em',
          padding: '2.5em 2em 2em 2em',
          round: '2.6em',
          background: 'linear-gradient(140deg, rgba(224, 77, 77, .15), rgba(0, 0, 0, 0.2))',
          color: 'white',
          cursor: 'pointer',
          boxShadow: `0 10px 30px rgba(0, 0, 0, 0.15),
  inset 0 0 0 0.08em rgba(255, 255, 255, 0.1)`,
          Hgroup: {
            extends: 'Hgroup',
            H3: {
              extends: 'H3',
              tag: 'h3',
              text: 'social media marketing',
              fontSize: '2.5em',
              fontWeight: '900',
              maxWidth: '7.5em',
              lineHeight: 'var(--lh-tight)',
              letterSpacing: 'var(--tracking-tight)',
              textTransform: 'uppercase',
              color: 'rgba(255, 241, 227, 0.75)',
              'body[data-lang="ka"] &': {
                fontFamily: "'BPG Square Banner Caps 2013', sans-serif",
                fontStyle: 'normal',
                fontWeight: '400',
                textTransform: 'none',
                fontSynthesis: 'none',
                WebkitFontSmoothing: 'antialiased',
                lineHeight: '1em',
              },
            },
            P: {
              extends: 'P',
              tag: 'p',
              text: 'Content creation and advertising',
              margin: '-',
              fontSize: '1.15em',
              maxWidth: '12em',
              lineHeight: 'var(--lh-compact)',
              paddingTop: '1.6em',
              color: 'rgba(255, 241, 227, 0.5)',
              'body[data-lang="ka"] &': { maxWidth: '13em' },
            },
          },
          UL: {
            extends: 'UL',
            tag: 'ul',
            class: 'service-content',
            listStyle: 'none',
            margin: '1.5em 0 0 0',
            padding: '0',
            display: 'flex',
            flexWrap: 'wrap',
            gap: '1em',
            maxWidth: '100%',
            paddingLeft: '0',
          },
          Button: {
            extends: 'Button',
            tag: 'button',
            font: 'inherit',
            background: 'rgba(224, 77, 77, 0.95)',
            border: 'none',
            cursor: 'pointer',
            type: 'button',
            width: '3.7em',
            height: '3.7em',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: '100%',
            position: 'absolute',
            bottom: '.85em',
            right: '.85em',
            overflow: 'hidden',
            zIndex: '10',
            boxShadow: '0 10px 20px rgba(224, 77, 77, 0.35)',
            Img: {
              extends: 'Img',
              src: 'arrow.png',
              class: 'icon-arrow',
              width: '1.5em',
              position: 'absolute',
              inset: '0',
              margin: 'auto',
            },
            Img_1: {
              extends: 'Img',
              src: 'close.png',
              class: 'icon-close',
              width: '1.5em',
              position: 'absolute',
              inset: '0',
              margin: 'auto',
            },
          },
        },
      },
      Nav: {
        extends: 'Nav',
        class: 'navigationDots',
        tag: 'nav',
        '--dot-hit-size': '0.9em',
        '--dot-visual-size': '0.9em',
        '--dot-ring-size': '0.12em',
        position: 'fixed',
        top: '50%',
        left: '0',
        right: 'auto',
        transform: 'translateY(-50%)',
        zIndex: '30',
        opacity: '0',
        pointerEvents: 'none',
        transition: 'opacity 0.16s ease-in-out',
        display: 'flex',
        flexDirection: 'column',
        gap: '0.9em',
        alignItems: 'center',
        width: 'fit-content',
        'aria-label': 'Services navigation',
        '&.is-visible': {
          opacity: '1',
          pointerEvents: 'auto',
          transition: 'opacity 0.2s ease-in-out',
        },
        '@media (max-width: 1180px), (hover: none) and (pointer: coarse)': {
          position: 'relative',
          left: 'auto',
          right: 'auto',
          top: 'auto',
          bottom: 'auto',
          transform: 'none',
          width: 'fit-content',
          margin: '20px auto 0',
          zIndex: '12',
          opacity: '1',
          pointerEvents: 'auto',
          flexFlow: 'row',
          gap: '0.22em',
        },
        '@media (max-width: 1024px)': {
          '--dot-hit-size': '2.1em',
          '--dot-visual-size': '1em',
        },
        '@media (max-width: 560px)': {
          '--dot-hit-size': '2.25em',
          '--dot-visual-size': '1.1em',
        },
        Button: {
          class: 'dot',
          'aria-label': 'Service 1',
          extends: 'NavDot',
        },
        Button_1: {
          class: 'dot',
          'aria-label': 'Service 2',
          extends: 'NavDot',
        },
        Button_2: {
          class: 'dot',
          'aria-label': 'Service 3',
          extends: 'NavDot',
        },
        Button_3: {
          class: 'dot',
          'aria-label': 'Service 4',
          extends: 'NavDot',
        },
      },
    },
    Section_7: {
      extends: 'Section',
      class: 'steps',
      tag: 'section',
      position: 'relative',
      minHeight: '100em',
      padding: '9em 0 8em 0',
      H2: {
        extends: 'H2',
        tag: 'h2',
        text: 'Flow to Work',
        position: 'absolute',
        right: '3em',
        top: '1em',
        fontSize: '5em',
        zIndex: '2',
        fontWeight: '900',
        maxWidth: '4.6em',
        textAlign: 'right',
        lineHeight: '0.9em',
        letterSpacing: '-0.02em',
        color: 'rgba(255, 241, 227, 1)',
        willChange: 'transform',
        '@media (max-width: 1366px)': { right: '2em' },
        '@media (max-width: 1024px)': { right: '1em' },
        '@media (max-width: 560px)': { fontSize: '3.5em' },
        '@media (max-width: 350px)': { fontSize: '3.2em' },
      },
      '@media (max-width: 768px)': { minHeight: '80em' },
      '@media (max-width: 480px)': { minHeight: '72em' },
      Circle: {
        extends: 'Circle',
        class: 'circle',
        top: '50%',
        left: '0',
        '@media (max-width: 1024px)': { transform: 'translate(-300px, -35%) rotate(var(--steps-rot, 0deg))' },
        '@media (max-width: 860px)': { transform: 'translate(-350px, -35%) rotate(var(--steps-rot, 0deg))' },
        '@media (max-width: 768px)': { fontSize: '0.87em' },
        '@media (max-width: 560px)': { fontSize: '0.8em' },
        '@media (max-width: 480px)': { transform: 'translate(-300px, -35%) rotate(var(--steps-rot, 0deg))', fontSize: '0.7em' },
        '@media (max-width: 390px)': { fontSize: '0.65em' },
        '@media (max-width: 350px)': { transform: 'translate(-250px, -35%) rotate(var(--steps-rot, 0deg))', fontSize: '0.63em' },
        Dot: {
          extends: 'Dot',
          class: 'dot dot1',
          right: '7em',
          top: '4em',
          Hgroup: {
            extends: 'Hgroup',
            margin: '-10em 0 0 5em',
            color: 'rgba(255, 241, 227, 1)',
            H3: {
              extends: 'H3',
              tag: 'h3',
              text: '01',
              fontSize: '5em',
              fontWeight: '900',
            },
            P: {
              extends: 'P',
              tag: 'p',
              text: 'initial consultation',
              margin: '2em 0 0 3em',
              fontSize: '1.5em',
              letterSpacing: '-0.03em',
              minWidth: '10em',
              lineHeight: '1.1em',
              fontWeight: '300',
              color: 'rgba(255, 241, 227, 1)',
            },
          },
        },
        Dot_1: {
          extends: 'Dot',
          class: 'dot dot2',
          right: '-0.5em',
          top: '22em',
          Hgroup: {
            extends: 'Hgroup',
            margin: '-10em 0 0 5em',
            color: 'rgba(255, 241, 227, 1)',
            H3: {
              extends: 'H3',
              tag: 'h3',
              text: '02',
              fontSize: '5em',
              fontWeight: '900',
            },
            P: {
              extends: 'P',
              tag: 'p',
              text: 'Strategy development and implementation',
              margin: '2em 0 0 3em',
              fontSize: '1.5em',
              letterSpacing: '-0.03em',
              minWidth: '10em',
              lineHeight: '1.1em',
              fontWeight: '300',
              color: 'rgba(255, 241, 227, 1)',
            },
          },
        },
        Dot_2: {
          extends: 'Dot',
          class: 'dot dot3',
          right: '10em',
          bottom: '2.2em',
          Hgroup: {
            extends: 'Hgroup',
            margin: '-5em 0 0 12em',
            color: 'rgba(255, 241, 227, 1)',
            H3: {
              extends: 'H3',
              tag: 'h3',
              text: '03',
              fontSize: '5em',
              fontWeight: '900',
            },
            P: {
              extends: 'P',
              tag: 'p',
              text: 'Review and final refinement',
              margin: '2em 0 0 3em',
              fontSize: '1.5em',
              letterSpacing: '-0.03em',
              minWidth: '10em',
              lineHeight: '1.1em',
              fontWeight: '300',
              color: 'rgba(255, 241, 227, 1)',
            },
          },
        },
      },
    },
    Section_8: {
      extends: 'Section',
      class: 'team',
      tag: 'section',
      width: '100%',
      background: 'transparent',
      position: 'relative',
      padding: '0 0 20em 0',
      zIndex: '10',
      margin: '0 auto',
      maxWidth: '1366px',
      '@media (max-width: 860px)': { paddingBottom: '5em' },
      H2: {
        extends: 'H2',
        tag: 'h2',
        text: 'Our Team',
        fontSize: '5.5em',
        maxWidth: '2em',
        lineHeight: '0.8em',
        fontWeight: '900',
        position: 'relative',
        zIndex: '4',
        padding: '0 0 3em 2.5em',
        color: 'rgba(255, 241, 227, 0.5)',
        'body[data-lang="ka"] &': { lineHeight: '1em' },
        '@media (max-width: 1024px)': { fontSize: '4.5em', padding: '0 0 3em 1.5em' },
        '@media (max-width: 560px)': { fontSize: '3.5em', padding: '0 0 2em 1em' },
      },
      Contents: {
        extends: 'Contents',
        class: 'contents',
        id: 'about',
        '&.reveal-on-scroll': {
          opacity: '0',
          transform: 'translateX(var(--swim-x, 0em)) translateY(calc(1.2em + var(--team-parallax-y, 0em) + var(--swim-y, 0em))) rotate(var(--swim-r, 0deg))',
          transition: 'opacity 0.7s var(--ease-io) 0.1s, transform 0.7s var(--ease-io) 0.1s',
        },
        '&.reveal-on-scroll.is-visible': {
          opacity: '1',
          transform: 'translateX(var(--swim-x, 0em)) translateY(calc(var(--team-parallax-y, 0em) + var(--swim-y, 0em))) rotate(var(--swim-r, 0deg))',
        },
        TeamMember: {
          extends: 'TeamMember',
          class: 'teamMember',
          H6: {
            extends: 'H6',
            tag: 'h6',
            text: 'Founder',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'Giorgi',
          },
          Img: {
            extends: 'Img',
            tag: 'img',
            display: 'block',
            maxWidth: '100%',
            src: 'choni2.webp',
            alt: '',
            loading: 'lazy',
            decoding: 'async',
          },
        },
        TeamMember_1: {
          extends: 'TeamMember',
          class: 'teamMember',
          H6: {
            extends: 'H6',
            tag: 'h6',
            text: 'Project Manager',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'Liza',
          },
          Img: {
            extends: 'Img',
            tag: 'img',
            display: 'block',
            maxWidth: '100%',
            src: 'liza2.webp',
            alt: '',
            loading: 'lazy',
            decoding: 'async',
          },
        },
        TeamMember_2: {
          extends: 'TeamMember',
          class: 'teamMember',
          H6: {
            extends: 'H6',
            tag: 'h6',
            text: 'Graphic Designer',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'Mariami',
          },
          Img: {
            extends: 'Img',
            tag: 'img',
            display: 'block',
            maxWidth: '100%',
            src: 'mariami2.webp',
            alt: '',
            loading: 'lazy',
            decoding: 'async',
          },
        },
        TeamMember_3: {
          extends: 'TeamMember',
          class: 'teamMember',
          H6: {
            extends: 'H6',
            tag: 'h6',
            text: 'Videograph',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'Luka',
          },
          Img: {
            extends: 'Img',
            tag: 'img',
            display: 'block',
            maxWidth: '100%',
            src: 'luka2.webp',
            alt: '',
            loading: 'lazy',
            decoding: 'async',
          },
        },
      },
      NavArrows: {
        extends: 'NavArrows',
        class: 'navArrows',
        margin: '3em 13em 0 auto',
        gap: '1em',
        zIndex: '5',
        maxWidth: 'fit-content',
        '@media (max-width: 860px)': { margin: '3em 6em 0 auto' },
        '@media (max-width: 560px)': { margin: '1em 3em 0 auto' },
        '@media (max-width: 480px)': { margin: '0.5em auto 0 auto' },
        '@media (max-width: 350px)': { margin: '-1.5em auto 0 auto' },
        Button: {
          class: 'prev',
          'aria-label': 'Previous team member',
          extends: 'Button4',
          '@media (max-width: 560px)': { width: '3em', height: '3em' },
        },
        Button_1: {
          class: 'next',
          'aria-label': 'Next team member',
          extends: 'Button4',
          '@media (max-width: 560px)': { width: '3.6em', height: '3.6em' },
        },
      },
      Button: {
        extends: 'Button',
        class: 'more',
        text: 'know us better',
        tag: 'button',
        font: 'inherit',
        color: 'rgba(255, 241, 227, 1)',
        padding: '1.2em 2em',
        borderRadius: '5em',
        border: '1px solid rgba(255, 241, 227, 0.2)',
        margin: '3em auto 0 20em',
        fontSize: '1em',
        display: 'block',
        cursor: 'pointer',
        fontWeight: '700',
        background: 'none',
        transition: 'transform 0.5s cubic-bezier(0.4, 0, 0.2, 1), padding 0.5s cubic-bezier(0.4, 0, 0.2, 1), background 0.5s ease, border-radius 0.5s ease, border 0.5s ease, opacity 0.5s ease, color 0.5s ease',
        '&:hover': {
          opacity: '1',
          backgroundColor: 'rgba(224, 77, 77, 1)',
          transform: 'scale(1.05)',
          border: '1px solid rgba(255, 241, 227, 0)',
        },
        '@media (max-width: 1024px)': { margin: '3em auto 0 10em' },
        '@media (max-width: 860px)': { margin: '3em auto 0 5em' },
        '@media (max-width: 560px)': { margin: '3em auto 0 2em' },
        '@media (max-width: 480px)': { margin: '8em auto 0 auto' },
      },
    },
    Section_9: {
      extends: 'Section',
      class: 'testimonial',
      tag: 'section',
      maxWidth: 'fit-content',
      margin: '0 auto',
      height: 'fit-content',
      padding: '10em 0 18em 0',
      position: 'relative',
      zIndex: '100',
      width: '100%',
      '@media (max-width: 860px)': { paddingBottom: '5em' },
      '@media (max-width: 350px)': { width: '100%' },
      Title: {
        extends: 'Title',
        class: 'title',
        paddingRight: '30em',
        opacity: '0.6',
        transform: 'translateX(var(--swim-x, 0em)) translateY(calc(1.2em + var(--swim-y, 0em))) rotate(var(--swim-r, 0deg))',
        transition: 'transform 0.75s var(--ease-io)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        '.testimonial.is-active &': {
          transform: 'translateX(var(--swim-x, 0em)) translateY(var(--swim-y, 0em)) rotate(var(--swim-r, 0deg))',
        },
        '@media (max-width: 1024px)': { fontSize: '0.9em', marginLeft: '5em', maxWidth: 'fit-content', width: 'fit-content', minWidth: 'fit-content' },
        '@media (max-width: 768px)': { fontSize: '0.8em', marginLeft: '3em', marginBottom: '6em' },
        '@media (max-width: 560px)': { fontSize: '0.7em' },
        Img: {
          src: 'quotation-mark.png',
          extends: 'Img2',
          height: '7em',
          width: 'auto',
          maxWidth: 'none',
          marginLeft: '10em',
          marginBottom: '2em',
          transformOrigin: 'center center',
          'body[data-lang="ka"] &': { marginBottom: '3.5em' },
          '.testimonial.is-active &': { animation: 'none' },
          '.testimonial.is-active.is-scrolling &': { animation: 'quoteShake 1.8s cubic-bezier(0.2, 0, 0, 1) infinite' },
        },
        H3: {
          extends: 'H3',
          tag: 'h3',
          text: 'people talks',
          fontSize: '5em',
          fontWeight: '900',
          textTransform: 'capitalize',
          maxWidth: '2em',
          lineHeight: '1em',
        },
      },
      TestimonialContent: {
        extends: 'TestimonialContent',
        class: 'testimonialContent',
        width: 'fit-content',
        marginLeft: 'auto',
        marginTop: '13em',
        maxHeight: '45em',
        position: 'relative',
        isolation: 'isolate',
        '::before': { content: 'none' },
        '::after': { content: 'none' },
        '@media (max-width: 1024px)': { marginRight: '5em' },
        '@media (max-width: 768px)': { margin: '0 auto' },
        '@media (max-width: 560px)': { fontSize: '0.8em' },
        '@media (max-width: 350px)': { width: '100%' },
        Messages: {
          extends: 'Messages',
          class: 'messages',
          '@media (max-width: 350px)': { width: 'fit-content', margin: '0 auto' },
          P: {
            extends: 'P',
            tag: 'p',
            text: 'I had an excellent experience everything was done accurately and on time',
            margin: '-',
            'data-author': 'James Harisson',
          },
          P_1: {
            extends: 'P',
            tag: 'p',
            text: 'The team was responsive and execution quality was consistently high.',
            margin: '-',
            'data-author': 'Nina Carter',
          },
          P_2: {
            extends: 'P',
            tag: 'p',
            text: 'Strong communication and fast delivery through the whole process.',
            margin: '-',
            'data-author': 'Robert Allen',
          },
          P_3: {
            extends: 'P',
            tag: 'p',
            text: 'They understood the brief quickly and improved our results month by month.',
            margin: '-',
            'data-author': 'Maria Brown',
          },
          P_4: {
            extends: 'P',
            tag: 'p',
            text: 'Everything was clear, on schedule, and aligned with our business goals.',
            margin: '-',
            'data-author': 'David Smith',
          },
          P_5: {
            extends: 'P',
            tag: 'p',
            text: 'Creative ideas with practical implementation and measurable impact.',
            margin: '-',
            'data-author': 'Sophia Miller',
          },
          P_6: {
            extends: 'P',
            tag: 'p',
            text: 'Professional workflow, transparent updates, and great final output.',
            margin: '-',
            'data-author': 'Alex Johnson',
          },
        },
        Focus: {
          extends: 'Focus',
          class: 'focus',
          FocusCorner: {
            extends: 'FocusCorner',
          },
          FocusCorner_1: {
            extends: 'FocusCorner',
          },
          FocusCorner_2: {
            extends: 'FocusCorner',
          },
          FocusCorner_3: {
            extends: 'FocusCorner',
          },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: 'James harisson',
            '@media (max-width: 768px)': { right: '-70%', bottom: '5em', marginRight: '2em' },
            '@media (max-width: 480px)': { right: '-50%', bottom: '5em', marginRight: '2em' },
            '@media (max-width: 350px)': { right: '-70%', bottom: '5em', marginRight: '2em' },
          },
        },
        '@media (max-width: 350px)': { width: '90%' },
      },
    },
    Footer: {
      extends: 'Footer',
      tag: 'footer',
      paddingLeft: '7em',
      paddingBottom: 'calc(6em + var(--app-fixed-bottom-clearance, 0px))',
      '--footerGlow': '0',
      '@media (max-width: 1280px)': { paddingLeft: '5.5em' },
      '@media (max-width: 768px)': { paddingLeft: '3.5em' },
      '@media (max-width: 620px)': { paddingRight: '3.5em' },
      '@media (max-width: 480px)': { paddingLeft: '2em', paddingRight: '2em' },
      H2: {
        extends: 'H2',
        tag: 'h2',
        text: 'focus agency',
        fontSize: '6em',
        fontWeight: '900',
        color: 'rgba(255, 241, 227, 0.5)',
        textAlign: 'center',
        maxWidth: '3em',
        lineHeight: '0.8em',
        margin: '0 4em 2em auto',
        textTransform: 'capitalize',
        transform: 'translateX(var(--swim-x, 0em)) translateY(var(--swim-y, 0em)) rotate(var(--swim-r, 0deg))',
        transition: 'text-shadow 0.25s ease',
        willChange: 'transform',
        'body[data-lang="ka"] &': {
          fontFamily: "'Exo 2', sans-serif",
        },
        '@media (max-width: 1366px)': {
          fontSize: '5em',
          margin: '0 2em 2em auto',
        },
        '@media (max-width: 860px)': {
          fontSize: '3.5em',
        },
        '@media (max-width: 620px)': {
          margin: '0 0.5em 3.5em auto',
        },
      },
      Form: {
        extends: 'Form',
        tag: 'form',
        display: 'flex',
        flexFlow: 'column',
        maxWidth: 'fit-content',
        maxHeight: 'fit-content',
        position: 'relative',
        gap: '1em',
        padding: '0',
        marginBottom: '5em',
        action: 'https://formspree.io/f/xqeypeyg',
        method: 'POST',
        id: 'contact',
        Legend: {
          extends: 'Legend',
          tag: 'legend',
          text: 'have a question?',
          fontSize: '1.2em',
          color: 'rgba(255, 241, 227, .7)',
          fontWeight: '300',
          margin: '0 0 2em .5em',
        },
        Input: {
          extends: 'Input',
          tag: 'input',
          font: 'inherit',
          border: '1px solid rgba(255, 241, 227, .1)',
          fontSize: '1em',
          round: '2em',
          padding: '1em 1.5em',
          color: 'cream',
          margin: '0',
          background: 'transparent',
          minWidth: '15em',
          maxWidth: '15em',
          id: 'name',
          name: 'name',
          type: 'text',
          autocomplete: 'name',
          placeholder: 'name',
          '@media (max-width: 480px)': { minWidth: '100%', maxWidth: '100%' },
        },
        Input_2: {
          extends: 'Input',
          tag: 'input',
          font: 'inherit',
          border: '1px solid rgba(255, 241, 227, .1)',
          fontSize: '1em',
          round: '2em',
          padding: '1em 1.5em',
          color: 'cream',
          margin: '0',
          background: 'transparent',
          minWidth: '19em',
          maxWidth: '19em',
          id: 'email',
          name: 'email',
          type: 'email',
          autocomplete: 'email',
          placeholder: 'email',
          required: '',
          '@media (max-width: 480px)': { minWidth: '100%', maxWidth: '100%' },
        },
        Textarea: {
          extends: 'Textarea',
          tag: 'textarea',
          font: 'inherit',
          minWidth: '28em',
          maxWidth: '28em',
          padding: '1.2em 1.5em',
          background: 'transparent',
          border: '1px solid rgba(255, 241, 227, .1)',
          round: '2em',
          resize: 'none',
          color: 'cream',
          id: 'message',
          name: 'message',
          rows: '6',
          placeholder: 'shoot a message',
          required: '',
          '@media (max-width: 620px)': { minWidth: '100%' },
        },
        Button: {
          extends: 'Button',
          tag: 'button',
          text: 'send',
          font: 'inherit',
          width: 'fit-content',
          padding: '.75em 1.5em',
          background: 'rgba(224, 77, 77, 0.75)',
          color: 'white',
          fontSize: '1.1em',
          borderRadius: '3em',
          border: 'none',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          position: 'absolute',
          bottom: '.75em',
          right: '.75em',
          cursor: 'pointer',
          type: 'submit',
          transition: 'background 0.5s ease, transform 0.5s ease',
          ':hover': {
            background: 'rgba(224, 77, 77, 1)',
            transform: 'scale(1.05)',
          },
        },
        P: {
          extends: 'P',
          tag: 'p',
          margin: '-',
          position: 'absolute',
          left: '0',
          bottom: '-2.2em',
          color: 'rgba(255, 241, 227, .85)',
          fontSize: '0.84375em',
          paddingLeft: '-',
          lineHeight: '1.2',
          id: 'contact-status',
          role: 'status',
          'aria-live': 'polite',
          hidden: '',
        },
      },
      Contact: {
        extends: 'Contact',
        class: 'contact',
        marginLeft: '1em',
        H5: {
          extends: 'H5',
          tag: 'h5',
          text: 'call us any time',
          color: 'rgba(255, 241, 227, 0.5)',
          marginBottom: '0.5em',
          fontWeight: '300',
          fontSize: '1.1em',
        },
        P: {
          extends: 'P',
          tag: 'p',
          text: '+995 595 893 399',
          margin: '0',
          fontSize: '1.2em',
          color: 'rgba(255, 241, 227, 0.85)',
          marginBottom: '2em',
        },
        H5_2: {
          extends: 'H5',
          tag: 'h5',
          text: 'connect with us by email',
          color: 'rgba(255, 241, 227, 0.5)',
          marginBottom: '0.5em',
          fontWeight: '300',
          fontSize: '1.1em',
        },
        P_3: {
          extends: 'P',
          tag: 'p',
          text: 'gamarjoba@focusagency.ge',
          margin: '0',
          fontSize: '1.2em',
          color: 'rgba(255, 241, 227, 0.85)',
          marginBottom: '2em',
        },
        H5_4: {
          extends: 'H5',
          tag: 'h5',
          text: 'Follow us',
          color: 'rgba(255, 241, 227, 0.5)',
          marginBottom: '0.5em',
          fontWeight: '300',
          fontSize: '1.1em',
        },
        Nav: {
          extends: 'Nav',
          class: 'socialLinks',
          tag: 'nav',
          display: 'flex',
          flexDirection: 'row',
          gap: '1em',
          marginTop: '1em',
          Link: {
            extends: 'Link3',
            Img: {
              src: 'facebook.png',
              extends: 'Img2',
              height: '2em',
              maxWidth: 'none',
            },
          },
          Link_1: {
            extends: 'Link3',
            Img: {
              src: 'instagram.png',
              extends: 'Img2',
              height: '2em',
              maxWidth: 'none',
            },
          },
        },
      },
      Address: {
        extends: 'Address',
        class: 'address',
        position: 'relative',
        maxWidth: 'fit-content',
        padding: '10em',
        marginLeft: 'auto',
        marginRight: '7em',
        '@media (max-width: 1366px)': { marginRight: '0em' },
        '@media (max-width: 1280px)': { marginRight: '-3em', marginTop: '-15em' },
        '@media (max-width: 1135px)': { marginRight: '0', marginTop: '0', paddingRight: '3em', marginBottom: '5em' },
        '@media (max-width: 860px)': { paddingTop: '6em', marginRight: '3em', paddingBottom: '0' },
        '@media (max-width: 620px)': { paddingLeft: '0', paddingRight: '0', minWidth: '100%', maxWidth: '100%' },
        Hgroup: {
          extends: 'Hgroup',
          tag: 'hgroup',
          '@media (max-width: 860px)': { paddingBottom: '4em' },
          '@media (max-width: 620px)': { paddingLeft: '1em' },
          H5: {
            extends: 'H5',
            tag: 'h5',
            text: `you're welcome to visit us`,
            color: 'rgba(255, 241, 227, 0.5)',
            marginBottom: '1em',
            fontWeight: '300',
            fontSize: '1.1em',
          },
          P: {
            extends: 'P',
            tag: 'p',
            margin: '-',
            fontSize: '1.2em',
            color: 'rgba(255, 241, 227, 0.85)',
            maxWidth: '17em',
            Span: {
              tag: 'span',
              text: 'Tbilisi, Saburtalo',
              display: 'block',
              marginTop: '0.2em',
            },
            Span_1: {
              tag: 'span',
              text: 'Alexandre Khazbegi street N24 g',
              display: 'block',
              marginTop: '0.2em',
            },
          },
        },
        Img: {
          src: 'street.webp',
          extends: 'Img2',
          minWidth: '25em',
          height: '15em',
          borderRadius: '2em',
          position: 'absolute',
          boxSizing: 'content-box',
          border: '1px solid rgba(255, 241, 227, 0.1)',
          padding: '1em',
          willChange: 'transform, filter',
          top: '-10em',
          left: '-10em',
          objectFit: 'cover',
          maxWidth: 'none',
          '@media (max-width: 1280px)': { minWidth: '20em', top: '-10em', left: '0em' },
          '@media (max-width: 860px)': { margin: '0', top: 'initial', position: 'initial' },
          '@media (max-width: 480px)': { minWidth: '80%', maxWidth: '80%', height: '13em' },
          '@media (max-width: 375px)': { height: '10em' },
          '@media (max-width: 620px)': { right: '0' },
        },
        Img_2: {
          src: 'street2.webp',
          extends: 'Img2',
          minWidth: '25em',
          height: '15em',
          borderRadius: '2em',
          position: 'absolute',
          boxSizing: 'content-box',
          border: '1px solid rgba(255, 241, 227, 0.1)',
          padding: '1em',
          willChange: 'transform, filter',
          marginTop: '3em',
          marginLeft: '-5em',
          objectFit: 'cover',
          maxWidth: 'none',
          '@media (max-width: 1280px)': { minWidth: '20em' },
          '@media (max-width: 860px)': { margin: '0', top: 'initial', position: 'initial' },
          '@media (max-width: 480px)': { minWidth: '80%', maxWidth: '80%', height: '13em' },
          '@media (max-width: 375px)': { height: '10em' },
          '@media (max-width: 620px)': { marginLeft: 'auto' },
        },
      },
      P: {
        extends: 'P',
        tag: 'p',
        text: `Our agency was founded with one main purpose — to support growth and success of businesses. Every client is
        unique to us, which is why we always listen carefully to your needs and create strategies that deliver real
        results.`,
        margin: '-',
        display: 'block',
        width: '100%',
        maxWidth: 'min(100%, 28em)',
        paddingRight: '1em',
        paddingBottom: '3em',
        marginTop: '8em',
        fontWeight: '300',
        fontSize: '3.5em',
        lineHeight: '0.84',
        color: 'rgba(255, 241, 227, 0.75)',
        overflowWrap: 'normal',
        wordBreak: 'normal',
        hyphens: 'none',
        '& .wave-char': { display: 'inline-block', opacity: '0.25', transition: 'opacity 0.25s ease' },
        '& .wave-word': { display: 'inline-block', whiteSpace: 'nowrap' },
        '&.is-wave-active .wave-char': { animation: 'footerTextWave 2.4s linear infinite', animationDelay: 'calc(var(--char-index) * 0.035s)' },
        '@media (max-width: 620px)': {
          maxWidth: '100%',
          margin: '1.1em 0 0',
          paddingRight: '0.2em',
        },
        '@media (max-width: 480px)': {
          paddingRight: '0',
        },
        '@media (max-width: 350px)': {
          paddingLeft: '0.2em',
        },
      },
    },
  },
};